version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 3
  reviewers:
    - emirkabal
  assignees:
    - emirkabal
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
